name: Build magiskboot

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip unzip wget git curl build-essential clang

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          rustc --version
          cargo --version

      - name: Setup Magisk NDK
        run: |
          python3 build.py ndk

      - name: Build native binaries (magiskboot etc.)
        run: |
          source $HOME/.cargo/env
          python3 build.py native

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: magiskboot
          path: native/magiskboot/magiskboot
