name: Build magiskboot

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      # 1. 拉取 Magisk 源码并初始化 submodule
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      # 2. 安装依赖
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip unzip wget git build-essential clang curl

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      # 4. 下载 Magisk NDK
      - name: Setup Magisk NDK
        run: python3 build.py ndk

      # 5. 编译 native 二进制（magiskboot 等）
      - name: Build native binaries
        run: |
          source $HOME/.cargo/env
          python3 build.py native

      # 6. 上传 magiskboot 作为 artifact
      - name: Upload magiskboot
        uses: actions/upload-artifact@v4
        with:
          name: magiskboot
          path: native/magiskboot/magiskboot
